name = "Quantikz"
uuid = "b0d11df0-eea3-4d79-b4a5-421488cbf74b"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]
version = "1.4.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Ghostscript_jll = "61579ee1-b43e-5ca0-a5da-69d92c66a64b"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
tectonic_jll = "d7dd28d6-a5e6-559c-9131-7eb760cdacc5"


[compat]
FileIO = "1.6"
Ghostscript_jll = "9.53"
ImageMagick = "1.1"
julia = "1.11"
tectonic_jll = "0.11"
